### PR TITLE
EGL support

### LINKED ISSUE #451: Missing EGL support for Wayland
see this thread in [coin3d-discuss](https://groups.google.com/g/coin3d-discuss/c/osGzMf4RW80)

### PR DESCRIPTION
**Pull request by epuzanov**
This PR Closes #451 Issue by adding EGL support for the Coin library. Use COIN_BUILD_EGL option to force EGL build.

### CODE REVIEW

**Comment by VolkerEnderlein** [comment]
Thank you so much Egor, your contribution to Coin development is highly appreciated. I'll test the commits over the next few days and will report back.

**Comment by VolkerEnderlein** [comment]
I did not found any issues with your current implementation so I merged it to the master branch. This is really a highly valuable contribution, thanks again for your work.

**Comment by epuzanov** [comment]
Hi Volker, I still have a problem with EGL Initialization under Wayland (under X11 it seems to work). In all my tests (using quarter or SoQT) the function cc_glglue_context_create_offscreen is not be called. Can you point me, how coin3d library initialized display or which component used for display initialization?

**Comment by VolkerEnderlein** [comment]
Hi Egor, I'll have a look and try to find out.

**Comment by VolkerEnderlein** [comment]
As I understand it, all viewer classes of SoQt and Quarter are finally derived from QGLWidget and QOpenGLWidget (dependent on Qt-Version). Therefore I suppose the EGL initialization must be done somehow by Qt. In some Coin classes offscreen contexts are created by calling `cc_glglue_context_create_offscreen` but that's the stuff you already ported and surely know about. I stumbled about a QtWayland plugin but did not tried to run it. The Qt wiki contains some additional [information](https://wiki.qt.io/QtWayland) on the plugin and the repo some examples. Sorry, I am out of knowledge here.

**Comment by luzpaz** [comment]
Once this code is stabilized, can Coin3D cut a new release so this fix is propagated downstream?

**Comment by VolkerEnderlein** [comment]
Yes, we'll prepare a release with all the bug fixes so far.

**Comment by epuzanov** [comment]
As for now, the EGL support is not a production ready. We need to fix EGL context initialization first.
@VolkerEnderlein can you reopen this PR?

**Comment by VolkerEnderlein** [comment]
It seems I was somewhat overzealous when merging and closing the PR. Unfortunately as I rebased and merged the PR I am not able to reopen it. From my limited Git knowledge there are two actions I can take: either moving the 3 commits to a new branch `egl` and hard reset the master or cherry pick the commits to a new branch `egl` and revert the commits in master. Either way we would need to open a new PR on this issue. What Do you think would be appropriate?

**Comment by VolkerEnderlein** [comment]
OK, I'll revert the 3 commits and await your new PR.

**Comment by VolkerEnderlein** [comment]
Hi Egor, while checking your commits, I noticed two minor issues.  glglue_cleanup was missing a call to eglglue_cleanup, and discard.h.in file was missing an #undef HAVE_EGL statement. Just wanted to let you know in case you did not found them already.

**Pull request merged**
