### PR TITLE
Fixed bug (crash) when call to cc_flww32_get_bitmap() fails

### PR DESCRIPTION
**Pull request by Renreok**
I would like to ask you to review a change in the Coin font handling.

Currently, Coin will crash when it fails to read a glyph either from the freetype library or from Win32. Although there is some error handling in place (Coin reads the glyph from the built-in default font), there are two problems:
- it does not mark the glyph as "fromdefaultfont", which causes several functions to fail (e.g. cc_flw_get_bitmap_advance() will return invalid information about how to advance to the next glyph in a text) and it will crash when it tries to free the glyph bitmap memory (fontstruct_rmglyph)
- glyphs from the default font use a different reference line than other fonts. The default font uses the descender line, while other fonts usually use the base line.

The first problem can be solved by properly setting the "fromdefaultfont" flag. I did quite some code review and testing, and I think that setting this flag truely solves the problem.

The second problem can be solved by setting the "bearing" for the default font in the same way as for fonts that use the freetype library or Win32 API. Note that this change will change the rendering output of any Coin program that uses the default font. However, I think it makes sense to have consistent behavior of all fonts.

Here is some Illustration, how text will be rendered before and after my fix (default font is rendered on the left, while "Times New Roman" is rendered on the Right).

old
new

P.S. The reason why I need this fix is that in my project we observe sporadic issues with the GetGlyphOutline Win32 function, which fails sporadically. I'm still trying to find the root cause for the failure of this function, but I think it still makes sense to fix the issues with the Coin font handling.

### CODE REVIEW

**Comment by veelo** [comment]
In principle, I support the change to base line positioning. It is consistent, and I think it is what people expect.

Hypothetically, there could be an application that lines out labels with objects (like the annotation of dimensions in a technical drawing), and in this case the current positioning helps legibility because the slight vertical separation is independent of zoom level (but dependent on font size). I am not aware of a way to offset text dependent on font size, so I think this application would have trouble attaining the same effect.

It would not affect any of my projects negatively (and I do use text). Would this be a problem for FreeCAD, @kkremitzki?

**Comment by veelo** [comment]
Anyway, before this gets accepted, please add a clear notice in https://github.com/coin3d/coin/blob/master/RELNOTES so that users are properly informed of the change.

Thanks!

**Comment by kkremitzki** [comment]
It would be good to do some testing of this with FreeCAD, but I may not be able to get to it before the weekend. I will create a thread in the FreeCAD forums asking if anyone is available to test this to make sure nothing breaks.

**Comment by Renreok** [comment]
Thank you very much for your replies. It is not urgent to merge this change, it should be a deliberate decision.
It would also be an option to introduce a compiler switch, but too many build switches can also be confusing. To me the inconsistent behavior feels more like a bug, so my initial proposal is without build switch.

Thanks for the hint about the RELNOTES file, Bastiaan. I really like that we maintain release notes now.

**Comment by Renreok** [comment]
Im currently working on the update of the RELNOTES file. Before I commit, I'd like to ask about the Coin version we are now working on (4.0.1?) and whether I should also adapt the NEWS file.

**Comment by kkremitzki** [comment]
IMO, no need for the NEWS file for this sort of change, and the current version should be 4.1.0.

**Comment by veelo** [comment]
> Im currently working on the update of the RELNOTES file. Before I commit, I'd like to ask about the Coin version we are now working on (4.0.1?) and whether I should also adapt the NEWS file.

I'd like you to add a line to the NEWS file, with a reference to RELNOTES for details and possibly this PR (for the images).

We haven't started working with different branches yet for different versions, which we probably should consider when changes pick up pace. According to https://semver.org/ I'd say the change in positioning is a minor change, i.e., targeting 4.1.0. If only the crash were addressed then 4.0.1 would be more appropriate, but IMO there is no need to be pedantic about this.

**Comment by Renreok** [comment]
I updated the pull request with changes to the NEWS and RELNOTES files. Please have a look.

Regarding branching: I think we should decide about the version we are targeting with the master branch (it seems currently 4.1.0), and also update the version defines (e.g. in config.h) accordingly.

**Comment by Renreok** [comment]
Please let me know if you need more time to analyze the Impact of this change.
If there are no objections, I will merge this pull request at the end of this week.

**Pull request merged**
