### PR TITLE
Adding environment variable COIN_GLX_PIXMAP_DIRECT_RENDERING to control direct rendering option for offscreen contexts

### PR DESCRIPTION
**Pull request by ytterx**
Proposed fix for #505
Probably needs more testing on various systems and configurations

### CODE REVIEW

**Comment by ytterx** [comment]
@VolkerEnderlein Hi, you seem to be the most recent contributor that merged a pull-request. Is is possible for you to take a look at this issue?

**Comment by VolkerEnderlein** [comment]
Probably something linke that:

```
Bool direct_rendering = False;
static int check_direct = -1;
if (check_direct == -1) {
  check_direct = 0;
  const char * env = coin_getenv("COIN_GLX_PIXMAP_DIRECT_RENDERING");
  direct_rendering = env && atoi(env) == 1 ? True : False;
}

context->glxcontext = glXCreateContext(display, context->visinfo, 0, direct_rendering);
```

**Comment by ytterx** [comment]
That might be a workable approach. I was hoping I could detect that it would not work and then allow for an automated switch but I wasn't able to do something like that. I'll make the suggested changes to my Pull-Request and test it in our environment.

**Comment by VolkerEnderlein** [comment]
I just noticed, the direct_rendering variable must be static too. Otherwise it works only for the first time but not for subsequent calls.

**Comment by ytterx** [comment]
Made the required changes, also added the information to the documentation

**Comment by VolkerEnderlein** [comment]
Thanks @ytterx for providing the necessary changes. Your contribution to Coin development is highly appreciated.

**Pull request merged**
