### PR TITLE
Readme: Switch to Markdown, add a diagram

### PR DESCRIPTION
**Pull request by veelo**
Supersedes #439.

### CODE REVIEW

**Comment by veelo** [comment]
Preview: https://github.com/coin3d/coin/blob/a19d9783c0f386326967da3b6baf9a5b26830bdd/README.md

**Comment by Vanuan** [comment]
Please add a white background, it doesn't look well in dark mode:

Screenshot_20210210-172940

**Comment by Vanuan** [comment]
Also, fonts are not nice for some reason

**Comment by veelo** [comment]
@Vanuan Can you check the background here? https://github.com/coin3d/coin/blob/1c3980b744d30ba7f4d671219d8621dd551ea20b/README.md

**Comment by veelo** [comment]
> Also, fonts are not nice for some reason

Yes I see that too. At first I thought this was due to low resolution, but this is actually fairly high dpi. It looks good on desktop in both Chrome and Edge. The selected font family is just "sans-serif", nothing fancy. Are you running the latest OS?.

**Comment by Vanuan** [comment]
Looks good now 
Screenshot_20210213-191643

**Comment by Vanuan** [comment]
Have you deliberately made asterisks of a different color from the text they refer to?

**Comment by veelo** [comment]
> Have you deliberately made asterisks of a different color from the text they refer to?

Yes. Same as the footnote.

**Comment by veelo** [comment]
Changed to white asterisks.

**Pull request merged**
